import { PlayerProfile, MatchHistoryItem, LeaderboardEntry, ShopItem, Quest, Tournament, Friend } from '../types';

const STORAGE_KEY_PROFILE = 'apex_arena_player_profile';
const STORAGE_KEY_HISTORY = 'apex_arena_match_history';
const STORAGE_KEY_QUESTS = 'apex_arena_daily_quests';
const STORAGE_KEY_SETTINGS = 'apex_arena_settings';

export const INITIAL_PROFILE: PlayerProfile = {
  id: 'usr_apex_9024',
  username: 'ValkyriePrime',
  tag: '#7701',
  avatar: '⚡',
  title: 'Grandmaster Contender',
  banner: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%)',
  level: 14,
  xp: 3850,
  xpToNextLevel: 5000,
  coins: 4850,
  gems: 190,
  twoFactorEnabled: true,
  cloudSyncHash: 'sha256-e9a8f273b018',
  lastSyncedAt: new Date().toISOString(),
  isOfflineMode: false,
  ratings: {
    chess: 1680,
    racing: 1740,
    cards: 1610,
    overall: 1676,
  },
  stats: {
    totalMatches: 48,
    totalWins: 32,
    winStreak: 4,
    bestStreak: 9,
    chessWins: 14,
    chessLosses: 6,
    chessDraws: 2,
    racingFirstPlaces: 11,
    racingBestTime: '01:14.32',
    cardBlackjacks: 9,
    cardBiggestPot: 2400,
  },
  equipped: {
    chessSkin: 'chess_cyber_neon',
    carSkin: 'car_phantom_gt',
    cardDeck: 'deck_hologram_matrix',
  },
  inventory: [
    'chess_default',
    'chess_cyber_neon',
    'car_default',
    'car_phantom_gt',
    'deck_classic',
    'deck_hologram_matrix',
    'title_apex_legend',
    'title_speed_demon',
  ],
};

export const INITIAL_MATCH_HISTORY: MatchHistoryItem[] = [
  {
    id: 'mat_001',
    game: 'CHESS',
    opponentName: 'KasparovBot99',
    opponentAvatar: '♟️',
    opponentRating: 1665,
    result: 'VICTORY',
    ratingDelta: +18,
    duration: '06:42',
    date: 'Today, 20:14',
    antiCheatScore: 100,
    verified: true,
    replayData: {
      summary: 'Aggressive Italian Game leading to a tactical queen-knight battery checkmate on f7.',
      chessMoves: [
        { moveIndex: 1, color: 'w', notation: 'e4', from: [6, 4], to: [4, 4], piece: 'p', commentary: 'King pawn opening establishing center control' },
        { moveIndex: 2, color: 'b', notation: 'e5', from: [1, 4], to: [3, 4], piece: 'p', commentary: 'Black mirrors in the center' },
        { moveIndex: 3, color: 'w', notation: 'Nf3', from: [7, 6], to: [5, 5], piece: 'n', commentary: 'Knight develops and attacks e5' },
        { moveIndex: 4, color: 'b', notation: 'Nc6', from: [0, 1], to: [2, 2], piece: 'n', commentary: 'Knight defends central e5 pawn' },
        { moveIndex: 5, color: 'w', notation: 'Bc4', from: [7, 5], to: [4, 2], piece: 'b', commentary: 'Italian Game aiming at vulnerable f7 weakness' },
        { moveIndex: 6, color: 'b', notation: 'Bc5', from: [0, 5], to: [3, 2], piece: 'b', commentary: 'Giuoco Piano standard development' },
        { moveIndex: 7, color: 'w', notation: 'c3', from: [6, 2], to: [5, 2], piece: 'p', commentary: 'Prepares d4 strike in the center' },
        { moveIndex: 8, color: 'b', notation: 'Nf6', from: [0, 6], to: [2, 5], piece: 'n', commentary: 'Black pressures White e4 pawn' },
        { moveIndex: 9, color: 'w', notation: 'd4', from: [6, 3], to: [4, 3], piece: 'p', commentary: 'Center pawn tension break' },
        { moveIndex: 10, color: 'b', notation: 'exd4', from: [3, 4], to: [4, 3], piece: 'p', captured: 'p', commentary: 'Black captures on d4' },
        { moveIndex: 11, color: 'w', notation: 'cxd4', from: [5, 2], to: [4, 3], piece: 'p', captured: 'p', commentary: 'Recaptured, maintaining two center pawns' },
        { moveIndex: 12, color: 'b', notation: 'Bb4+', from: [3, 2], to: [4, 1], piece: 'b', isCheck: true, commentary: 'Check delivered to White king' },
        { moveIndex: 13, color: 'w', notation: 'Nc3', from: [7, 1], to: [5, 2], piece: 'n', commentary: 'Aggressive piece development over defense' },
        { moveIndex: 14, color: 'b', notation: 'Nxe4', from: [2, 5], to: [4, 4], piece: 'n', captured: 'p', commentary: 'Black grabs the central pawn' },
        { moveIndex: 15, color: 'w', notation: 'O-O', from: [7, 4], to: [7, 6], piece: 'k', commentary: 'White castles kingside, rook enters e-file' },
        { moveIndex: 16, color: 'b', notation: 'Bxc3', from: [4, 1], to: [5, 2], piece: 'b', captured: 'n', commentary: 'Black exchanges bishop for knight' },
        { moveIndex: 17, color: 'w', notation: 'bxc3', from: [6, 1], to: [5, 2], piece: 'p', captured: 'b', commentary: 'White recaptures towards center' },
        { moveIndex: 18, color: 'b', notation: 'd5', from: [1, 3], to: [3, 3], piece: 'p', commentary: 'Black stakes center claim' },
        { moveIndex: 19, color: 'w', notation: 'Ba3!', from: [7, 2], to: [5, 0], piece: 'b', commentary: 'Deadly diagonal preventing Black from castling!' },
        { moveIndex: 20, color: 'b', notation: 'dxc4', from: [3, 3], to: [4, 2], piece: 'p', captured: 'b', commentary: 'Black takes the bishop, falling into the trap' },
        { moveIndex: 21, color: 'w', notation: 'Re1', from: [7, 5], to: [7, 4], piece: 'r', commentary: 'Pins Black knight directly to king' },
        { moveIndex: 22, color: 'b', notation: 'Be6', from: [0, 2], to: [2, 4], piece: 'b', commentary: 'Desperate block on e-file' },
        { moveIndex: 23, color: 'w', notation: 'Rxe4', from: [7, 4], to: [4, 4], piece: 'r', captured: 'n', commentary: 'White material regained with decisive initiative' },
        { moveIndex: 24, color: 'b', notation: 'Qd5', from: [0, 3], to: [3, 3], piece: 'q', commentary: 'Queen centralized' },
        { moveIndex: 25, color: 'w', notation: 'Qe2', from: [7, 3], to: [6, 4], piece: 'q', commentary: 'Tripling heavy pieces along e-file' },
        { moveIndex: 26, color: 'b', notation: 'O-O-O', from: [0, 4], to: [0, 2], piece: 'k', commentary: 'Black escapes to queenside' },
        { moveIndex: 27, color: 'w', notation: 'Re8#', from: [4, 4], to: [0, 4], piece: 'r', isCheck: true, commentary: 'Back-rank penetration checkmate! Victory!' },
      ],
    },
  },
  {
    id: 'mat_002',
    game: 'CAR_RACING',
    opponentName: 'ApexDrifter_JP',
    opponentAvatar: '🏎️',
    opponentRating: 1720,
    result: 'VICTORY',
    ratingDelta: +24,
    duration: '02:31',
    date: 'Today, 18:45',
    antiCheatScore: 99,
    verified: true,
    replayData: {
      summary: 'Masterful drift recovery on Sector 2 followed by a triple-canister Nitro sprint to take 1st place.',
      racingTelemetry: [
        { timeSec: 0, speedMph: 0, position: 5, lap: 1, event: 'Race Start Countdown: Green Light' },
        { timeSec: 12, speedMph: 145, position: 4, lap: 1, event: 'Overtook ZenithDrift into Turn 1' },
        { timeSec: 28, speedMph: 178, position: 3, lap: 1, event: 'Collected Nitro Canister #1' },
        { timeSec: 46, speedMph: 165, position: 3, lap: 2, event: 'Lap 1 Completed: 00:46.21' },
        { timeSec: 62, speedMph: 215, position: 2, lap: 2, event: 'Nitro Boost Activated! Overtook Solaris_GT' },
        { timeSec: 85, speedMph: 195, position: 2, lap: 2, event: 'Slingshot Boost Pad triggered' },
        { timeSec: 104, speedMph: 170, position: 2, lap: 3, event: 'Final Lap Flag Displayed' },
        { timeSec: 125, speedMph: 232, position: 1, lap: 3, event: 'Drift Pass on ApexDrifter_JP for P1 lead!' },
        { timeSec: 142, speedMph: 228, position: 1, lap: 3, event: 'Top Speed record reached (232 MPH)' },
        { timeSec: 151, speedMph: 210, position: 1, lap: 3, event: 'Checkered Flag: 1st Place Victory!' },
      ],
    },
  },
  {
    id: 'mat_003',
    game: 'CARD_GAME',
    opponentName: 'NeonAce_99',
    opponentAvatar: '🃏',
    opponentRating: 1640,
    result: 'DEFEAT',
    ratingDelta: -14,
    duration: '04:15',
    date: 'Yesterday, 22:30',
    antiCheatScore: 100,
    verified: true,
    replayData: {
      summary: 'High-stakes round where dealer held soft 17 and drew an Ace for 20 against player 19.',
      cardSteps: [
        {
          step: 1,
          description: 'Initial Deal: Player receives King of Spades and 9 of Hearts. Dealer shows 7 of Diamonds.',
          playerCards: [{ suit: '♠', rank: 'K' }, { suit: '♥', rank: '9' }],
          dealerCards: [{ suit: '♦', rank: '7' }, { suit: '♣', rank: '10', hidden: true }],
          playerScore: 19,
          dealerScore: 7,
        },
        {
          step: 2,
          description: 'Player Decision: Strong 19 locked. Player chooses to STAND.',
          playerCards: [{ suit: '♠', rank: 'K' }, { suit: '♥', rank: '9' }],
          dealerCards: [{ suit: '♦', rank: '7' }, { suit: '♣', rank: '10', hidden: true }],
          playerScore: 19,
          dealerScore: 7,
        },
        {
          step: 3,
          description: 'Dealer Turn: Dealer flips hidden hole card (10 of Clubs), showing 17 total.',
          playerCards: [{ suit: '♠', rank: 'K' }, { suit: '♥', rank: '9' }],
          dealerCards: [{ suit: '♦', rank: '7' }, { suit: '♣', rank: '10' }],
          playerScore: 19,
          dealerScore: 17,
        },
        {
          step: 4,
          description: 'Dealer Draw: Dealer draws 3 of Spades, making 20. Dealer wins by 1 point.',
          playerCards: [{ suit: '♠', rank: 'K' }, { suit: '♥', rank: '9' }],
          dealerCards: [{ suit: '♦', rank: '7' }, { suit: '♣', rank: '10' }, { suit: '♠', rank: '3' }],
          playerScore: 19,
          dealerScore: 20,
        },
      ],
    },
  },
  {
    id: 'mat_004',
    game: 'CHESS',
    opponentName: 'GrandmasterShadow',
    opponentAvatar: '👑',
    opponentRating: 1790,
    result: 'VICTORY',
    ratingDelta: +29,
    duration: '09:12',
    date: 'Yesterday, 21:05',
    antiCheatScore: 100,
    verified: true,
    replayData: {
      summary: 'Grandmaster Queen Sacrifice into smothered knight checkmate.',
      chessMoves: [
        { moveIndex: 1, color: 'w', notation: 'd4', from: [6, 3], to: [4, 3], piece: 'p', commentary: 'Queen pawn opening' },
        { moveIndex: 2, color: 'b', notation: 'Nf6', from: [0, 6], to: [2, 5], piece: 'n', commentary: 'Indian defense setup' },
        { moveIndex: 3, color: 'w', notation: 'c4', from: [6, 2], to: [4, 2], piece: 'p', commentary: 'Space advantage in center' },
        { moveIndex: 4, color: 'b', notation: 'e6', from: [1, 4], to: [2, 4], piece: 'p', commentary: 'Preparing Nimzo or Queen Indian' },
        { moveIndex: 5, color: 'w', notation: 'Nc3', from: [7, 1], to: [5, 2], piece: 'n', commentary: 'Developing knight' },
        { moveIndex: 6, color: 'b', notation: 'Bb4', from: [0, 5], to: [4, 1], piece: 'b', commentary: 'Nimzo-Indian pin' },
        { moveIndex: 7, color: 'w', notation: 'e3', from: [6, 4], to: [5, 4], piece: 'p', commentary: 'Solid Rubinstein system' },
        { moveIndex: 8, color: 'b', notation: 'O-O', from: [0, 4], to: [0, 6], piece: 'k', commentary: 'Black castles' },
        { moveIndex: 9, color: 'w', notation: 'Nf3', from: [7, 6], to: [5, 5], piece: 'n', commentary: 'Kingside development' },
        { moveIndex: 10, color: 'b', notation: 'd5', from: [1, 3], to: [3, 3], piece: 'p', commentary: 'Direct challenge to center' },
        { moveIndex: 11, color: 'w', notation: 'Bd3', from: [7, 5], to: [5, 3], piece: 'b', commentary: 'Bishop eyes h7' },
        { moveIndex: 12, color: 'b', notation: 'c5', from: [1, 2], to: [3, 2], piece: 'p', commentary: 'Double tension in center' },
        { moveIndex: 13, color: 'w', notation: 'O-O', from: [7, 4], to: [7, 6], piece: 'k', commentary: 'King safeties secured' },
        { moveIndex: 14, color: 'b', notation: 'Nc6', from: [0, 1], to: [2, 2], piece: 'n', commentary: 'Classical development' },
        { moveIndex: 15, color: 'w', notation: 'a3', from: [6, 0], to: [5, 0], piece: 'p', commentary: 'Asking question of the bishop' },
        { moveIndex: 16, color: 'b', notation: 'Bxc3', from: [4, 1], to: [5, 2], piece: 'b', captured: 'n', commentary: 'Bishop exchanged' },
        { moveIndex: 17, color: 'w', notation: 'bxc3', from: [6, 1], to: [5, 2], piece: 'p', captured: 'b', commentary: 'Recaptured' },
        { moveIndex: 18, color: 'b', notation: 'Qc7', from: [0, 3], to: [1, 2], piece: 'q', commentary: 'Queen aligns on c-file' },
        { moveIndex: 19, color: 'w', notation: 'Ng5!', from: [5, 5], to: [3, 6], piece: 'n', commentary: 'Greek gift sacrifice preparatory probe' },
        { moveIndex: 20, color: 'b', notation: 'h6', from: [1, 7], to: [2, 7], piece: 'p', commentary: 'Kicking the knight' },
        { moveIndex: 21, color: 'w', notation: 'Bxh7+!', from: [5, 3], to: [1, 7], piece: 'b', captured: 'p', isCheck: true, commentary: 'The classic Greek Gift bishop sacrifice!' },
        { moveIndex: 22, color: 'b', notation: 'Kh8', from: [0, 6], to: [0, 7], piece: 'k', commentary: 'Black ducks into the corner' },
        { moveIndex: 23, color: 'w', notation: 'Qh5', from: [7, 3], to: [4, 7], piece: 'q', commentary: 'Overwhelming attack on h-file' },
        { moveIndex: 24, color: 'b', notation: 'Nxh7', from: [2, 5], to: [1, 7], piece: 'n', captured: 'b', commentary: 'Black captures the sacrifice' },
        { moveIndex: 25, color: 'w', notation: 'Qxf7#', from: [4, 7], to: [1, 5], piece: 'q', captured: 'p', isCheck: true, commentary: 'Devastating infiltration checkmate!' },
      ],
    },
  },
];

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  {
    id: 'lead_1',
    rank: 1,
    previousRank: 1,
    username: 'MagnusDrift',
    tag: '#0001',
    avatar: '👑',
    tier: 'Grandmaster',
    rating: 2480,
    winRate: 84.5,
    matchesPlayed: 412,
    region: 'EU',
    isFriend: false,
    isSelf: false,
  },
  {
    id: 'lead_2',
    rank: 2,
    previousRank: 3,
    username: 'CipherSpeed',
    tag: '#1337',
    avatar: '⚡',
    tier: 'Grandmaster',
    rating: 2390,
    winRate: 81.2,
    matchesPlayed: 380,
    region: 'NA',
    isFriend: true,
    isSelf: false,
  },
  {
    id: 'lead_3',
    rank: 3,
    previousRank: 2,
    username: 'HoloQueen',
    tag: '#4421',
    avatar: '💎',
    tier: 'Grandmaster',
    rating: 2315,
    winRate: 78.9,
    matchesPlayed: 320,
    region: 'APAC',
    isFriend: false,
    isSelf: false,
  },
  {
    id: 'lead_4',
    rank: 4,
    previousRank: 5,
    username: 'TurboBishop',
    tag: '#9012',
    avatar: '🚀',
    tier: 'Master',
    rating: 2180,
    winRate: 74.0,
    matchesPlayed: 245,
    region: 'EU',
    isFriend: true,
    isSelf: false,
  },
  {
    id: 'lead_5',
    rank: 5,
    previousRank: 4,
    username: 'ValkyriePrime',
    tag: '#7701',
    avatar: '⚡',
    tier: 'Platinum',
    rating: 1676,
    winRate: 66.7,
    matchesPlayed: 48,
    region: 'NA',
    isFriend: false,
    isSelf: true,
  },
  {
    id: 'lead_6',
    rank: 6,
    previousRank: 6,
    username: 'AceDealers',
    tag: '#2209',
    avatar: '🃏',
    tier: 'Platinum',
    rating: 1650,
    winRate: 63.8,
    matchesPlayed: 110,
    region: 'APAC',
    isFriend: false,
    isSelf: false,
  },
  {
    id: 'lead_7',
    rank: 7,
    previousRank: 8,
    username: 'ApexRonin',
    tag: '#8841',
    avatar: '🔥',
    tier: 'Gold',
    rating: 1540,
    winRate: 59.4,
    matchesPlayed: 92,
    region: 'NA',
    isFriend: true,
    isSelf: false,
  },
  {
    id: 'lead_8',
    rank: 8,
    previousRank: 7,
    username: 'NeonPawn',
    tag: '#3144',
    avatar: '🛡️',
    tier: 'Gold',
    rating: 1490,
    winRate: 55.1,
    matchesPlayed: 88,
    region: 'EU',
    isFriend: false,
    isSelf: false,
  },
];

export const INITIAL_SHOP_ITEMS: ShopItem[] = [
  {
    id: 'chess_cyber_neon',
    name: 'Cyber Neon Pieces',
    game: 'CHESS',
    type: 'SKIN',
    rarity: 'Epic',
    price: 1500,
    currency: 'COINS',
    previewColor: '#06b6d4',
    description: 'Electric cyan and neon magenta pieces with illuminated edge glows.',
  },
  {
    id: 'chess_obsidian_gold',
    name: 'Obsidian & Imperial Gold',
    game: 'CHESS',
    type: 'SKIN',
    rarity: 'Legendary',
    price: 250,
    currency: 'GEMS',
    previewColor: '#eab308',
    description: 'Forged obsidian black pieces accented with 24k polished gold crowns.',
  },
  {
    id: 'car_phantom_gt',
    name: 'Phantom GT Stealth Racer',
    game: 'CAR_RACING',
    type: 'SKIN',
    rarity: 'Epic',
    price: 2000,
    currency: 'COINS',
    previewColor: '#8b5cf6',
    description: 'Carbon-fiber aerodynamic chassis equipped with purple plasma exhaust trail.',
  },
  {
    id: 'car_solar_mclaren',
    name: 'Solar Flare Hypercar',
    game: 'CAR_RACING',
    type: 'SKIN',
    rarity: 'Legendary',
    price: 350,
    currency: 'GEMS',
    previewColor: '#f97316',
    description: 'Radiant orange metallic finish with blazing ember particle boosters.',
  },
  {
    id: 'deck_hologram_matrix',
    name: 'Hologram Matrix Deck',
    game: 'CARD_GAME',
    type: 'SKIN',
    rarity: 'Epic',
    price: 1200,
    currency: 'COINS',
    previewColor: '#10b981',
    description: 'Prismatic foil cards with animated digital back pattern.',
  },
  {
    id: 'deck_royal_gold',
    name: 'Crown Royal High-Roller',
    game: 'CARD_GAME',
    type: 'SKIN',
    rarity: 'Legendary',
    price: 200,
    currency: 'GEMS',
    previewColor: '#f59e0b',
    description: 'Opulent gold-foil filigree cards designed for VIP high-stakes tables.',
  },
  {
    id: 'title_apex_legend',
    name: 'Title: "Apex Legend"',
    game: 'ALL',
    type: 'TITLE',
    rarity: 'Legendary',
    price: 150,
    currency: 'GEMS',
    previewColor: '#ec4899',
    description: 'Prestige title displayed proudly on leaderboards and in matchmaking.',
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'qst_1',
    title: 'Blitz Tactician',
    description: 'Win 1 match in Grandmaster Blitz Chess',
    targetCount: 1,
    currentCount: 0,
    rewardType: 'COINS',
    rewardAmount: 600,
    game: 'CHESS',
    claimed: false,
  },
  {
    id: 'qst_2',
    title: 'Speed Demon',
    description: 'Finish a Nitro Apex race in under 01:25.00',
    targetCount: 1,
    currentCount: 1,
    rewardType: 'COINS',
    rewardAmount: 500,
    game: 'CAR_RACING',
    claimed: false,
  },
  {
    id: 'qst_3',
    title: 'High-Stakes Dealer',
    description: 'Score a Natural Blackjack in Cyber 21',
    targetCount: 1,
    currentCount: 0,
    rewardType: 'GEMS',
    rewardAmount: 25,
    game: 'CARD_GAME',
    claimed: false,
  },
  {
    id: 'qst_4',
    title: 'Global Contender',
    description: 'Play 3 multiplayer matches in any game',
    targetCount: 3,
    currentCount: 2,
    rewardType: 'XP',
    rewardAmount: 750,
    game: 'ALL',
    claimed: false,
  },
];

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: 'trn_1',
    name: 'Apex Daily Blitz Championship',
    game: 'CHESS',
    status: 'LIVE',
    startTime: 'Today, 21:00 UTC',
    entryFee: 200,
    currency: 'COINS',
    prizePool: { coins: 15000, gems: 250 },
    participantsCount: 64,
    maxParticipants: 64,
    userRegistered: true,
    bracketStage: 'Semifinals',
    matches: [
      { id: 'm1', round: 'Quarterfinals', player1: 'ValkyriePrime', player2: 'NeonPawn', score1: 1, score2: 0, winner: 'ValkyriePrime' },
      { id: 'm2', round: 'Quarterfinals', player1: 'MagnusDrift', player2: 'TurboBishop', score1: 1, score2: 0, winner: 'MagnusDrift' },
      { id: 'm3', round: 'Semifinals', player1: 'ValkyriePrime', player2: 'CipherSpeed', score1: 0, score2: 0 },
      { id: 'm4', round: 'Semifinals', player1: 'MagnusDrift', player2: 'HoloQueen', score1: 0, score2: 0 },
    ],
  },
  {
    id: 'trn_2',
    name: 'Neon Tokyo Grand Prix',
    game: 'CAR_RACING',
    status: 'UPCOMING',
    startTime: 'Tomorrow, 16:00 UTC',
    entryFee: 50,
    currency: 'GEMS',
    prizePool: { coins: 30000, gems: 800 },
    participantsCount: 48,
    maxParticipants: 64,
    userRegistered: false,
    bracketStage: 'Quarterfinals',
    matches: [],
  },
  {
    id: 'trn_3',
    name: 'Midnight Cyber 21 Invitational',
    game: 'CARD_GAME',
    status: 'UPCOMING',
    startTime: 'In 3 Days, 23:00 UTC',
    entryFee: 500,
    currency: 'COINS',
    prizePool: { coins: 20000, gems: 400 },
    participantsCount: 32,
    maxParticipants: 32,
    userRegistered: false,
    bracketStage: 'Quarterfinals',
    matches: [],
  },
];

export const INITIAL_FRIENDS: Friend[] = [
  {
    id: 'frd_1',
    name: 'CipherSpeed',
    tag: '#1337',
    avatar: '⚡',
    status: 'IN_MATCH',
    currentGame: 'CAR_RACING',
    rating: 2390,
  },
  {
    id: 'frd_2',
    name: 'TurboBishop',
    tag: '#9012',
    avatar: '🚀',
    status: 'ONLINE',
    rating: 2180,
  },
  {
    id: 'frd_3',
    name: 'ApexRonin',
    tag: '#8841',
    avatar: '🔥',
    status: 'ONLINE',
    rating: 1540,
  },
  {
    id: 'frd_4',
    name: 'SilentRook',
    tag: '#0491',
    avatar: '🛡️',
    status: 'OFFLINE',
    rating: 1420,
  },
];

// Profile storage helper
export function loadProfile(): PlayerProfile {
  try {
    const data = localStorage.getItem(STORAGE_KEY_PROFILE);
    if (data) return JSON.parse(data);
  } catch {}
  return INITIAL_PROFILE;
}

export function saveProfile(profile: PlayerProfile): void {
  try {
    const updated = {
      ...profile,
      lastSyncedAt: new Date().toISOString(),
      cloudSyncHash: 'sha256-' + Math.random().toString(36).substring(2, 12),
    };
    localStorage.setItem(STORAGE_KEY_PROFILE, JSON.stringify(updated));
  } catch {}
}

export function loadMatchHistory(): MatchHistoryItem[] {
  try {
    const data = localStorage.getItem(STORAGE_KEY_HISTORY);
    if (data) return JSON.parse(data);
  } catch {}
  return INITIAL_MATCH_HISTORY;
}

export function saveMatchHistory(history: MatchHistoryItem[]): void {
  try {
    localStorage.setItem(STORAGE_KEY_HISTORY, JSON.stringify(history));
  } catch {}
}

export function loadQuests(): Quest[] {
  try {
    const data = localStorage.getItem(STORAGE_KEY_QUESTS);
    if (data) return JSON.parse(data);
  } catch {}
  return INITIAL_QUESTS;
}

export function saveQuests(quests: Quest[]): void {
  try {
    localStorage.setItem(STORAGE_KEY_QUESTS, JSON.stringify(quests));
  } catch {}
}
